services:
  react_app:
    container_name: react_app
    build: ./front-end
    image: react_app_image
    volumes:
      - build_react:/var/www/html

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    image: nginx_app_image
    volumes:
      - build_react:/var/www/html

volumes:
  - build_react
